const EXAM_DATA = [
  {
    id: '1-1',
    title: '1. Dönem 1. Sınav Hazırlık',
    summary: '<b>Domain ve Hosting Temelleri:</b> Domain, sitenin internetteki adıdır; IP adreslerini isimlere çeviren teknoloji <b>DNS</b>\'dir. <b>Hosting</b>, dosyaların saklandığı sunucu alanıdır. <br><br><b>WordPress ve Local Server:</b> Yerel çalışma için <b>XAMPP</b> (Apache ve MySQL) kurulmalıdır. <br><br><b>Yönetim Paneline Erişim:</b> Genellikle `wp-admin` adresi üzerinden erişilir. <br><br><b>Kullanıcı Rolleri:</b> <b>Yönetici</b> (en yetkili), <b>Editör</b> (içerik kontrolü), <b>Yazar</b> (kendi yazıları), <b>İçerik Sağlayıcı</b> ve <b>Abone</b> rolleridir.',
    questions: [
      { q: "Domain ve hosting olmadan bir web sitesi yayınlanabilir mi?", a: "Hayır." },
      { q: ".edu uzantısı neyi temsil eder?", a: "Eğitim kurumlarını." },
      { q: "WordPress kurulumunda wp-config.php ne işe yarar?", a: "Veri tabanı bağlantı ayarlarını tutar." },
      { q: "Kullanıcı rolleri içinde en geniş yetkiye sahip olan hangisidir?", a: "Yönetici." },
      { q: "İçerik Sağlayıcı rolü görsel yükleyebilir mi?", a: "Hayır." },
      { q: "Bir yazıyı yayınlamadan sadece belirli kişilere şifreyle göstermek için hangi ayar kullanılır?", a: "Parola Korumalı." },
      { q: "WordPress'in varsayılan içerik editörü nedir?", a: "Gutenberg." },
      { q: "Bir blogun en üstüne bir yazıyı sabitlemek için ne yapılır?", a: "Blogun en üstüne sabitle seçeneği işaretlenir." },
      { q: "IP adresini domain adresine çeviren teknoloji nedir?", a: "DNS." },
      { q: "Bir kullanıcı oluşturulurken hangi alanın girilmesi zorunludur?", a: "Kullanıcı adı ve e-posta." }
    ],
    flashcards: [
      { front: "Domain", back: "Web sitesinin internetteki adı." },
      { front: "Hosting", back: "Web sitesi dosyalarının saklandığı sunucu alanı." },
      { front: "IP Adresi", back: "İnternet sitelerinin rakamlardan oluşan benzersiz adresi." },
      { front: "DNS", back: "IP adreslerini alan adlarına çeviren sistem." },
      { front: "XAMPP", back: "Yerel bilgisayarda sunucu ortamı kuran program." },
      { front: "wp-admin", back: "WordPress yönetim paneli giriş adresi." },
      { front: "Veri Tabanı", back: "Sitedeki yazı ve ayarların saklandığı yer." },
      { front: "PHP", back: "WordPress'in yazıldığı programlama dili." },
      { front: "Yönetici", back: "Sitedeki her türlü işlemi yapabilen en yetkili rol." },
      { front: "Editör", back: "Başkalarının yazılarını düzenleyip yayınlayabilen rol." },
      { front: "Yazar", back: "Sadece kendi yazılarını yazıp yayınlayabilen rol." },
      { front: "İçerik Sağlayıcı", back: "Kendi yazısını yazar ama yayınlayamaz." },
      { front: "Abone", back: "Sadece kendi profilini güncelleyebilen en düşük yetkili rol." },
      { front: "Gutenberg", back: "WordPress'in blok tabanlı yeni içerik editörü." },
      { front: "Blok Yerleştirici (+)", back: "Yazıya yeni bloklar eklemeyi sağlar." },
      { front: "Taslağı Kaydet", back: "Yazıyı yayınlamadan kaydetme işlemi." },
      { front: "Önizleme", back: "Yazının yayınlanmadan önceki son halini görme." },
      { front: "Site Başlığı", back: "Tarayıcı çubuğunda görünen sitenin adı." },
      { front: "Slogan", back: "Sitenin ne hakkında olduğunu açıklayan kısa ifade." },
      { front: "localhost", back: "Yerel bilgisayardaki sunucu adresi." }
    ]
  },
  {
    id: '1-2',
    title: '1. Dönem 2. Sınav Hazırlık',
    summary: '<b>Yazılar ve Sayfalar:</b> <b>Yazılar</b> dinamik (kategorili), <b>Sayfalar</b> ise sabit (Hakkımızda vb.) içeriklerdir. <br><br><b>Gutenberg Editörü:</b> Blok tabanlı bir editördür; her öge (başlık, paragraf, resim) bir <b>blok</b>tur. <br><br><b>Kategori İşlemleri:</b> Yazılar mutlaka bir kategoriye bağlanmalıdır; seçilmezse <b>Varsayılan Kategori</b>ye atanır. <br><br><b>Menü Tasarımı:</b> Site navigasyon araçlarıdır. Sayfalar, yazılar veya <b>Özel Bağlantılar</b> eklenebilir.',
    questions: [
      { q: "Sayfalar kategorilere bağlanabilir mi?", a: "Hayır." },
      { q: "Bir kategoriyi silince içindeki yazılar da silinir mi?", a: "Hayır, varsayılan kategoriye atanır." },
      { q: "WordPress'te varsayılan kategori silinebilir mi?", a: "Hayır." },
      { q: "Menüden bir sayfa silindiğinde o sayfa siteden de silinir mi?", a: "Hayır, sadece bağlantısı kalkar." },
      { q: "Bir yazı birden fazla kategoriye atanabilir mi?", a: "Evet." },
      { q: "Çöp kutusuna atılan bir yazı kaç gün sonra kalıcı olarak silinir?", a: "30 gün." },
      { q: "Yazı Kısa İsmi (Slug) belirlenirken neye dikkat edilmelidir?", a: "Türkçe karakter kullanılmamalı ve kelimeler arası tire konmalıdır." },
      { q: "Menü isimleri nereden değiştirilir?", a: "Görünüm > Menüler > Dolaşım Etiketi." },
      { q: "Yazı istatistiklerini (karakter, kelime sayısı) hangi simge gösterir?", a: "Info (i) simgesi." },
      { q: "Özel görünürlük seçeneği neyi sağlar?", a: "Sadece editör ve yazarların yazıyı görmesini sağlar." }
    ],
    flashcards: [
      { front: "Yazı", back: "Haber, blog veya makale gibi dinamik içerikler." },
      { front: "Sayfa", back: "Hakkımızda, iletişim gibi statik (sabit) içerikler." },
      { front: "Kategori", back: "Yazıları konularına göre gruplandırma aracı." },
      { front: "Etiket", back: "Yazı içeriğini tanımlayan anahtar kelimeler." },
      { front: "Öne Çıkan Görsel", back: "Yazı listelerinde başlığın yanında çıkan resim." },
      { front: "Kalıcı Bağlantı", back: "Yazının internetteki sabit linki (URL)." },
      { front: "Özet", back: "Yazının baş kısmında veya RSS servislerinde görünen kısa metin." },
      { front: "Tartışma", back: "Yazıya yorum yapılıp yapılamayacağını belirleyen bölüm." },
      { front: "Alt Kategori", back: "Bir ana kategoriye bağlı olan kategori." },
      { front: "Varsayılan Kategori", back: "Kategori seçilmediğinde sistemin otomatik atadığı kategori." },
      { front: "Menü", back: "Sitedeki bağlantıların listelendiği navigasyon alanı." },
      { front: "Menü Konumu", back: "Menünün sitenin neresinde (üst, alt, yan) görüneceği." },
      { front: "Özel Bağlantılar", back: "Menüye dış bir link (URL) ekleme özelliği." },
      { front: "Dolaşım Etiketi", back: "Menüde görünen başlığın adı." },
      { front: "Hızlı Düzenle", back: "Yazıyı açmadan başlık ve kategori değişikliği yapma." },
      { front: "Çöp Kutusu", back: "Silinen içeriklerin 30 gün beklediği yer." },
      { front: "Hiyerarşi", back: "Kategorilerin ana-alt ilişkisi kurması." },
      { front: "Statik İçerik", back: "Zamanla değişmeyen, sayfa yapısındaki içerik." },
      { front: "Dinamik İçerik", back: "Sürekli güncellenen blog gönderileri." },
      { front: "Galeri Bloku", back: "Birden fazla görseli düzenli gösterme bloku." }
    ]
  },
  {
    id: '2-1',
    title: '2. Dönem 1. Sınav Hazırlık',
    summary: '<b>Tema İşlemleri:</b> Görünümü belirler; değişiklik öncesi <b>yedek</b> alınmalıdır. <br><br><b>Tema Kod Yapısı:</b> Görsellik için <b>style.css</b>, özellikler için <b>functions.php</b> kullanılır. <br><br><b>Eklentiler (Plugins):</b> Sisteme SEO, hız, güvenlik gibi yeni işlevler katan kod paketleridir. <br><br><b>Eklenti Kodlama:</b> Eklentiler <b>PHP</b> dili ile yazılır ve `wp-content/plugins` klasöründe yer alır.',
    questions: [
      { q: "Tema değiştirirken ilk yapılması gereken nedir?", a: "Sitenin yedeğini almak." },
      { q: "Sitenin renk ayarlarını değiştirmek için hangi dosya düzenlenir?", a: "style.css." },
      { q: "Bir eklentiyi silmek için önce ne yapılmalıdır?", a: "Etkisizleştirilmelidir." },
      { q: "İstenmeyen yorumları otomatik filtreleyen varsayılan eklenti hangisidir?", a: "Akismet Anti-Spam." },
      { q: "Yorum el ile onaylanmalı ayarı neyi sağlar?", a: "Tüm yorumların yönetici onayından geçmesini zorunlu kılar." },
      { q: "Ortam kütüphanesindeki bir resmi tamamen silince ne olur?", a: "Diskte yer açılır ve resim yazıdan kalkar." },
      { q: "Bir eklentinin kodlarını düzenlemek için hangi menü kullanılır?", a: "Eklenti Dosya Düzenleyicisi." },
      { q: "SEO nedir?", a: "Arama Motoru Optimizasyonu." },
      { q: "Yorum yaparken isim ve e-posta zorunluluğu nereden ayarlanır?", a: "Ayarlar > Tartışma." },
      { q: "Gravatar nedir?", a: "WordPress yorumlarında görünen kullanıcı profil resmi." }
    ],
    flashcards: [
      { front: "Tema", back: "Web sitesinin dış görünümünü belirleyen tasarım paketi." },
      { front: "style.css", back: "Temanın stil (renk, yazı tipi) dosyası." },
      { front: "functions.php", back: "Temaya yeni özellikler ekleyen dosya." },
      { front: "header.php", back: "Sitenin üst bölümünü (logo, menü) yöneten dosya." },
      { front: "footer.php", back: "Sitenin en alt (telif hakkı) bölümünü yöneten dosya." },
      { front: "Eklenti (Plugin)", back: "WordPress'e yeni işlevler katan kod paketleri." },
      { front: "Akismet", back: "İstenmeyen (spam) yorumları engelleyen eklenti." },
      { front: "SEO Eklentisi", back: "Sitenin arama motorlarında üst sıraya çıkmasını sağlar." },
      { front: "Caching (Önbellek)", back: "Sitenin daha hızlı açılmasını sağlayan yöntem." },
      { front: "API Anahtarı", back: "Akismet gibi servisleri aktifleştiren özel kod." },
      { front: "Tartışma Ayarları", back: "Yorum kurallarının belirlendiği menü." },
      { front: "Spam Yorum", back: "Arama motoru kandırmak için atılan sahte yorumlar." },
      { front: "Onaylı Yorum", back: "Yönetici tarafından kabul edilen ve yayınlanan yorum." },
      { front: "Ortam Kütüphanesibi", back: "Siteye yüklenen tüm resim ve videoların listesi." },
      { front: "Küçük Resim", back: "Görsellerin 150x150 boyutundaki hali." },
      { front: "Dışa Aktar", back: "Site içeriğini XML dosyası olarak indirme." },
      { front: "Hello Dolly", back: "WordPress ile gelen rastgele sözler gösteren eklenti." },
      { front: "Klasik Düzenleyici", back: "Gutenberg öncesi eski yazı editörü eklentisi." },
      { front: "Kademeli Yorumlar", back: "Yoruma yapılan yanıtların seviye sınırı." },
      { front: "Otomatik Güncelleme", back: "Eklentilerin yeni sürümlerinin sistemce yüklenmesi." }
    ]
  },
  {
    id: '2-2',
    title: '2. Dönem 2. Sınav Hazırlık',
    summary: '<b>Yorum Yönetimi:</b> <b>Tartışma Ayarları</b> üzerinden yönetilir. Spamlar için <b>Akismet</b> kullanılır. <br><br><b>Ortam Kütüphanesi:</b> Tüm medya dosyaları burada saklanır. <br><br><b>Siber Saldırılar:</b> <b>SQL Injection</b> (veritabanı), <b>DDoS</b> (aşırı trafik) ve <b>XSS</b> (kod çalıştırma) en yaygın olanlardır. <br><br><b>Gelişmiş Güvenlik:</b> <b>XML-RPC</b> kapatılmalı ve <b>reCAPTCHA</b> kurulmalıdır. Kritik ayarlar için `.htaccess` ve `wp-config.php` kullanılır.',
    questions: [
      { q: "WordPress tabanlı sitelerde neden admin kullanıcı adı kullanılmamalıdır?", a: "Kaba kuvvet saldırılarını zorlaştırmak için." },
      { q: "DDoS saldırısının temel amacı nedir?", a: "Sunucuyu aşırı yükleyerek hizmet veremez hale getirmek." },
      { q: "XML-RPC neden devre dışı bırakılmalıdır?", a: "DDoS saldırıları için açık bir kapı olabildiği için." },
      { q: "Veri tabanı güvenliği için en önemli işlem nedir?", a: "Düzenli yedek almak." },
      { q: "reCAPTCHA'da V2 ve V3 arasındaki fark nedir?", a: "V2 işlem bekler, V3 arka planda kullanıcıyı rahatsız etmeden çalışır." },
      { q: "Bir saldırı sonrası siteyi eski haline getirmenin en hızlı yolu nedir?", a: "Yedeği geri yüklemek." },
      { q: "Hata ayıklama (Debug) modu neden kapalı tutulmalıdır?", a: "Saldırganlara kod yapısı hakkında ipucu vermemek için." },
      { q: "SQL Injection saldırısı nereyi hedef alır?", a: "Veri tabanını." },
      { q: "Siteye sadece belirli bir IP'den giriş izni vermek nerede yapılır?", a: ".htaccess dosyası üzerinden." },
      { q: "Dosya düzenleme editörü güvenlik için neden kapatılmalıdır?", a: "Panelden dosyaların içine zararlı kod enjekte edilmesini önlemek için." }
    ],
    flashcards: [
      { front: "Bilgi Güvenliği", back: "Gizlilik, bütünlük ve erişilebilirlik ilkeleri." },
      { front: "SQL Injection", back: "Veri tabanından izinsiz bilgi çalma yöntemi." },
      { front: "XSS (Cross-Site Scripting)", back: "Tarayıcıda izinsiz kod çalıştırma." },
      { front: "2FA", back: "Çift faktörlü doğrulama güvenliği." },
      { front: "DDoS", back: "Sunucuyu sahte isteklerle yanıt veremez hale getirme." },
      { front: "Botnet", back: "Korsanların kontrol ettiği zombi bilgisayar ağı." },
      { front: "XML-RPC", back: "Üçüncü taraf uygulamaların siteyle etkileşim protokolü." },
      { front: "htaccess", back: "Sunucu seviyesinde güvenlik ayarları yapan dosya." },
      { front: "IP Blocker", back: "Belirli IP adreslerinin siteye erişimini engelleme." },
      { front: "Firewall", back: "Yetkisiz erişimleri filtreleyen yazılım." },
      { front: "CDN", back: "İçeriği dünya geneline dağıtarak hızı ve güvenliği artıran ağ." },
      { front: "Brute Force", back: "Sürekli şifre deneyerek sızma girişimi." },
      { front: "Raw Access Logs", back: "Siteye gelen tüm ham erişim kayıtları." },
      { front: "Veri Tabanı Öneki", back: "Tabloların başındaki wp_ gibi belirteç." },
      { front: "CAPTCHA", back: "İnsan ve botu ayıran test." },
      { front: "reCAPTCHA", back: "Google'ın sunduğu Ben robot değilim testi." },
      { front: "SSL Sertifikası", back: "Veri trafiğini şifreleyen güvenlik belgesi." },
      { front: "Debug (Hata Ayıklama)", back: "Yazılımdaki hataları bulma modu." },
      { front: "wp-config.php", back: "Sitenin ana yapılandırma ve güvenlik dosyası." },
      { front: "Site Key", back: "reCAPTCHA kurulumu için gerekli anahtarlardan biri." }
    ]
  }
];

window.EXAM_DATA = EXAM_DATA;
